---

- name: Fetch cluster operators details
  shell: "oc get co"
  register: oplog
  until: "'AVAILABLE' in oplog.stdout"
  retries: 3
  delay: 3

- name: Process cluster operators details
  shell: |
    echo "{{ oplog.stdout }}" | awk '/PROGRESSING/,EOF {print $4}' | grep 'True' | wc -l
    echo "{{ oplog.stdout }}" | awk '/DEGRADED/,EOF {print $5}' | grep 'True' | wc -l
  register: opcount

- name: Fail upgrade process incase cluster state is unhealthy
  fail:
    msg: The current cluster state is unhealthy, upgrading it is not recommended. Please run 'oc get co' command for more details or try upgrade after sometime.
  when: opcount.stdout_lines[0]|int > 0 or opcount.stdout_lines[1]|int > 0

- name: Upgrade ocp to a stable version
  block:
     - name: Set upgrade channel
       when: upgrade_channel != ""
       shell: |
         oc patch clusterversion/version -p '{"spec":{"channel":"{{ upgrade_channel }}"}}' --type=merge

     - name: Upgrade cluster
       shell: |
         oc adm upgrade --to="{{ upgrade_version }}"

     - name: Waiting until upgrade completes
       pause:
         minutes: "{{ pause_time }}"

     - name: Check for upgrade completion
       shell: |
         oc get clusterversion -o json|jq ".items[0].status.history[0].state"
       register: state
       until: state.stdout | replace('\"', '') == "Completed"
       retries: 5
       delay: "{{ delay_time }}"
  when: upgrade_version != "" and upgrade_image == ""

- name: Upgrade ocp using a release image
  block:
     - name: Upgrade cluster
       shell: |
         oc adm upgrade --force --to-image="{{ upgrade_image }}" --allow-explicit-upgrade

     - name: Waiting until upgrade completes
       pause:
         minutes: "{{ pause_time }}"

     - name: Check for upgrade completion
       shell: |
         oc get clusterversion -o json|jq ".items[0].status.history[0].state"
       register: state
       until: state.stdout | replace('\"', '') == "Completed"
       retries: 5
       delay: "{{ delay_time }}"
  when: upgrade_image != ""
